spring.application.name=eureka

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

server.port=8761

#spring.main.banner-mode=off
#spring.main.log-startup-info=false
#logging.level.root=WARN
#logging.level.com.myapp=INFO
